### ISSUE TITLE
Bookmarklet vanishing on move

### ISSUE THREAD

**Issue by dejankozina** [ctomczyk/aslint#1]
Hello and thank you for the bookmarklet. I tried it with Firefox Portable 47 and I cannot move it around, as I try the thing vanishes and all the text on the page is selected...

**Comment by ctomczyk** [comment]
Hello. Thanks for feedback. Which OS you're using? I'll check how it work on Firefox Portable 47 on OS X.

**Comment by ctomczyk** [comment]
I've just tested ASLint on Firefox Portable 49.0.1 (Windows 10) and I couldn't see any errors there.

Can you provide more details with steps to reproduce the problem?

**Comment by dejankozina** [comment]
Sorry  for the botched title, just coming out of a bout of flu...
Well, it seems to work now. I'm on XP Pro SP3 and i tested right now with Firefox 49.0.1, Chrome  49.0.2623.112 m and Opera 36.0.2130.80 and it indeed moves around just fine. Then I tested again with Firefox Portable 47 and it works there too, even if I didn't restart or anything? Go figure.
Thank you again for aslint, I really like it: handy and easy to use and understand.
