### ISSUE TITLE
SSL Cert on aslint.org expired

### ISSUE THREAD

**Issue by xdesro** [ctomczyk/aslint#11]
Aloha! Getting the ol' "your connection is not private" error when visiting aslint.org, just wanted to let someone know in case it wasn't a known issue! 

```Your connection is not private
Attackers might be trying to steal your information from www.aslint.org (for example, passwords, messages, or credit cards). Learn more
```

Thanks!

**Comment by ctomczyk** [comment]
Yes. I am on it now. Thank you.

**Comment by xdesro** [comment]
Thanks for the swift response!

**Comment by ctomczyk** [comment]
Problem has been resolved. Website https://www.aslint.org/ should work fine now.
