### ISSUE TITLE
elements-not-allowed-in-head 

### ISSUE THREAD

**Issue by sandrina-p** [ctomczyk/aslint#3]
On [my website](http://sandrina-p.net) I have tag `<noscript>` and it is valid on [W3C Validator](https://validator.w3.org/), but aslint says it's not.

```
Expected <noscript></noscript> not to be as a child of <head>
XPath: XPath string 
/html/head/noscript
  
Impact: minor
```

Usually the <noscript> is not allowed on `<head>` except if its child is a `<style>` or `<link>` element, which is my case.

Source - [W3C - the style element](https://www.w3.org/TR/html5/document-metadata.html#the-style-element)

> Contexts in which this element can be used:
> - Where metadata content is expected.
> - In a `noscript` element that is a child of a `head` element.

Source - [W3C - the link element](https://www.w3.org/TR/html5/document-metadata.html#the-link-element)

> Contexts in which this element can be used:
> - Where metadata content is expected.
> - In a noscript element that is a child of a head element.

As you can see, on [my website](http://sandrina-p.net) the `<noscript>` element has only a `link` and a `style` children.

```
    <noscript>
        <link rel="stylesheet" href="src/index.min.css">
        <style>
            .noscript, .navCV, .chat, .js-psst { display:none!important; }
        </style>
    </noscript>
```

**Comment by ctomczyk** [comment]
You're right. I've updated the rule `elements-not-allowed-in-head` and with version 0.0.719 it should work correctly.

**Comment by sandrina-p** [comment]
Yap, the error is gone, thanks!
