### ISSUE TITLE
Expected unnecessary attribute roles 

### ISSUE THREAD

**Issue by sandrina-p** [ctomczyk/aslint#5]
Aslint gives an error when a role is not used in landmarks tags such as `<main>`, `<header>` and `<nav>`. 

```
Expected attribute role="navigation" to be defined on element <nav class="Nav js-Nav"></nav>
XPath: XPath string 
/html/body/main/div/nav
  
Impact: major
```

If I add those roles, the [w3c validator](https://validator.w3.org) will fail:
> The banner `navigation` is unnecessary for element `nav`.

I would suggest to remove this warning, because these roles are only needed on old browsers like IE6, and we are on 2017 😅

**Comment by ctomczyk** [comment]
The purpose of adding those roles was to help screen readers to understand the HTML5 tags. I remember that some of screen readers wasn't able to understand `<main>`, `<header>` and `<nav>` without adding appropriate `role` attribute.

However, yes - seems now it is quite well readable by VoiceOver, Windows Narrator and NVDA (with Firefox).

I will remove that rule.

**Comment by ctomczyk** [comment]
The rule has been removed in version v.0.0.698
