### ISSUE TITLE
For aslint, what test set (ruleset) is utilized?

### ISSUE THREAD

**Issue by jasonday** [ctomczyk/aslint#7]
Are you using Axe, etc?

**Comment by ctomczyk** [comment]
ASLint is using it's own rules written 100% by me and they are based on WCAG 2(.1), Section 508 and other cases not defined in WCAG or Section 508.

**Comment by jasonday** [comment]
Will you make that ruleset public in github? It might be helpful to allow the community to identify additional rules (best practices) and for transparency.

**Comment by ctomczyk** [comment]
Yes, I have a plan to publish the code this year.
