### ISSUE TITLE
ASlint as IDE plugin [feature request]

### ISSUE THREAD

**Issue by jasonday** [ctomczyk/aslint#9]
It would be awesome to have ASlint as an installable plugin for various code editors/IDEs.

- Visual Studio Code
- Atom.io
- Sublime Text
- etc. 

providing real time feedback to developers.

**Comment by ctomczyk** [comment]
I am not quite sure if that would be valuable. The trouble is that today's day the sources doesn't represent mostly what's in reality. I mean, there are templates where the final rendered HTML is quite different.

Therefore I think testing using ASLint should be done **always on real rendered application** as the sources aren't good place to test Accessibility features.

However, any others thoughts are very welcome.

**Comment by ctomczyk** [comment]
Closing it for now. However, I am open to discuss it anyway.
